apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
        - name: client-container
          image: lilianthiauru/yolo-client:1.0.0 
          ports:
            - containerPort: 3000

