apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-app
  ports:
    - name: client-port
      port: 3000
      targetPort: 3000
 
      nodePort: 31000
  type: LoadBalancer