apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-app
  ports:
    - name: backend-port
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer